### ISSUE TITLE
Merge ics parser & merger into master branch

### ISSUE THREAD

**Issue by zyzo** [fossasia/common.api.fossasia.net#5]
Now that the ics parser & merger is complete, what should I prepare to merge them in master branch ? Where should I put the PHP class ? Is there code review ? Should I go ahead and open a PR ?

**Comment by mariobehling** [comment]
@zyzo If the feature is finished make a pull request and Andi will review the code and merge it. If the feature is not yet finished keep it in a separate branch.

@andibraeu What about PHP? I was not aware we have PHP classes.

**Comment by andibraeu** [comment]
As @mariobehling said, when you think it's ready, create a pull request an I'll do the code review.

**Comment by andibraeu** [comment]
My wishes are: just create an own directory for it. Add a README to describe how to set it up and how to use it.

If there are configuration options (i.e. url to the directory) add a sample configuration file as we did for the generator
